	MebX_Qsys_Project u0 (
		.clk50_clk                                (<connected-to-clk50_clk>),                                //                   clk50.clk
		.rst_reset_n                              (<connected-to-rst_reset_n>),                              //                     rst.reset_n
		.spwc_a_enable_spw_rx_enable_signal       (<connected-to-spwc_a_enable_spw_rx_enable_signal>),       //           spwc_a_enable.spw_rx_enable_signal
		.spwc_a_enable_spw_tx_enable_signal       (<connected-to-spwc_a_enable_spw_tx_enable_signal>),       //                        .spw_tx_enable_signal
		.spwc_a_leds_spw_red_status_led_signal    (<connected-to-spwc_a_leds_spw_red_status_led_signal>),    //             spwc_a_leds.spw_red_status_led_signal
		.spwc_a_leds_spw_green_status_led_signal  (<connected-to-spwc_a_leds_spw_green_status_led_signal>),  //                        .spw_green_status_led_signal
		.spwc_a_lvds_spw_lvds_p_data_in_signal    (<connected-to-spwc_a_lvds_spw_lvds_p_data_in_signal>),    //             spwc_a_lvds.spw_lvds_p_data_in_signal
		.spwc_a_lvds_spw_lvds_n_data_in_signal    (<connected-to-spwc_a_lvds_spw_lvds_n_data_in_signal>),    //                        .spw_lvds_n_data_in_signal
		.spwc_a_lvds_spw_lvds_p_data_out_signal   (<connected-to-spwc_a_lvds_spw_lvds_p_data_out_signal>),   //                        .spw_lvds_p_data_out_signal
		.spwc_a_lvds_spw_lvds_n_data_out_signal   (<connected-to-spwc_a_lvds_spw_lvds_n_data_out_signal>),   //                        .spw_lvds_n_data_out_signal
		.spwc_a_lvds_spw_lvds_p_strobe_out_signal (<connected-to-spwc_a_lvds_spw_lvds_p_strobe_out_signal>), //                        .spw_lvds_p_strobe_out_signal
		.spwc_a_lvds_spw_lvds_n_strobe_out_signal (<connected-to-spwc_a_lvds_spw_lvds_n_strobe_out_signal>), //                        .spw_lvds_n_strobe_out_signal
		.spwc_a_lvds_spw_lvds_p_strobe_in_signal  (<connected-to-spwc_a_lvds_spw_lvds_p_strobe_in_signal>),  //                        .spw_lvds_p_strobe_in_signal
		.spwc_a_lvds_spw_lvds_n_strobe_in_signal  (<connected-to-spwc_a_lvds_spw_lvds_n_strobe_in_signal>),  //                        .spw_lvds_n_strobe_in_signal
		.spwc_b_enable_spw_rx_enable_signal       (<connected-to-spwc_b_enable_spw_rx_enable_signal>),       //           spwc_b_enable.spw_rx_enable_signal
		.spwc_b_enable_spw_tx_enable_signal       (<connected-to-spwc_b_enable_spw_tx_enable_signal>),       //                        .spw_tx_enable_signal
		.spwc_b_leds_spw_red_status_led_signal    (<connected-to-spwc_b_leds_spw_red_status_led_signal>),    //             spwc_b_leds.spw_red_status_led_signal
		.spwc_b_leds_spw_green_status_led_signal  (<connected-to-spwc_b_leds_spw_green_status_led_signal>),  //                        .spw_green_status_led_signal
		.spwc_b_lvds_spw_lvds_p_data_in_signal    (<connected-to-spwc_b_lvds_spw_lvds_p_data_in_signal>),    //             spwc_b_lvds.spw_lvds_p_data_in_signal
		.spwc_b_lvds_spw_lvds_n_data_in_signal    (<connected-to-spwc_b_lvds_spw_lvds_n_data_in_signal>),    //                        .spw_lvds_n_data_in_signal
		.spwc_b_lvds_spw_lvds_p_data_out_signal   (<connected-to-spwc_b_lvds_spw_lvds_p_data_out_signal>),   //                        .spw_lvds_p_data_out_signal
		.spwc_b_lvds_spw_lvds_n_data_out_signal   (<connected-to-spwc_b_lvds_spw_lvds_n_data_out_signal>),   //                        .spw_lvds_n_data_out_signal
		.spwc_b_lvds_spw_lvds_p_strobe_out_signal (<connected-to-spwc_b_lvds_spw_lvds_p_strobe_out_signal>), //                        .spw_lvds_p_strobe_out_signal
		.spwc_b_lvds_spw_lvds_n_strobe_out_signal (<connected-to-spwc_b_lvds_spw_lvds_n_strobe_out_signal>), //                        .spw_lvds_n_strobe_out_signal
		.spwc_b_lvds_spw_lvds_p_strobe_in_signal  (<connected-to-spwc_b_lvds_spw_lvds_p_strobe_in_signal>),  //                        .spw_lvds_p_strobe_in_signal
		.spwc_b_lvds_spw_lvds_n_strobe_in_signal  (<connected-to-spwc_b_lvds_spw_lvds_n_strobe_in_signal>),  //                        .spw_lvds_n_strobe_in_signal
		.spwc_c_enable_spw_rx_enable_signal       (<connected-to-spwc_c_enable_spw_rx_enable_signal>),       //           spwc_c_enable.spw_rx_enable_signal
		.spwc_c_enable_spw_tx_enable_signal       (<connected-to-spwc_c_enable_spw_tx_enable_signal>),       //                        .spw_tx_enable_signal
		.spwc_c_leds_spw_red_status_led_signal    (<connected-to-spwc_c_leds_spw_red_status_led_signal>),    //             spwc_c_leds.spw_red_status_led_signal
		.spwc_c_leds_spw_green_status_led_signal  (<connected-to-spwc_c_leds_spw_green_status_led_signal>),  //                        .spw_green_status_led_signal
		.spwc_c_lvds_spw_lvds_p_data_in_signal    (<connected-to-spwc_c_lvds_spw_lvds_p_data_in_signal>),    //             spwc_c_lvds.spw_lvds_p_data_in_signal
		.spwc_c_lvds_spw_lvds_n_data_in_signal    (<connected-to-spwc_c_lvds_spw_lvds_n_data_in_signal>),    //                        .spw_lvds_n_data_in_signal
		.spwc_c_lvds_spw_lvds_p_data_out_signal   (<connected-to-spwc_c_lvds_spw_lvds_p_data_out_signal>),   //                        .spw_lvds_p_data_out_signal
		.spwc_c_lvds_spw_lvds_n_data_out_signal   (<connected-to-spwc_c_lvds_spw_lvds_n_data_out_signal>),   //                        .spw_lvds_n_data_out_signal
		.spwc_c_lvds_spw_lvds_p_strobe_out_signal (<connected-to-spwc_c_lvds_spw_lvds_p_strobe_out_signal>), //                        .spw_lvds_p_strobe_out_signal
		.spwc_c_lvds_spw_lvds_n_strobe_out_signal (<connected-to-spwc_c_lvds_spw_lvds_n_strobe_out_signal>), //                        .spw_lvds_n_strobe_out_signal
		.spwc_c_lvds_spw_lvds_p_strobe_in_signal  (<connected-to-spwc_c_lvds_spw_lvds_p_strobe_in_signal>),  //                        .spw_lvds_p_strobe_in_signal
		.spwc_c_lvds_spw_lvds_n_strobe_in_signal  (<connected-to-spwc_c_lvds_spw_lvds_n_strobe_in_signal>),  //                        .spw_lvds_n_strobe_in_signal
		.spwc_d_enable_spw_rx_enable_signal       (<connected-to-spwc_d_enable_spw_rx_enable_signal>),       //           spwc_d_enable.spw_rx_enable_signal
		.spwc_d_enable_spw_tx_enable_signal       (<connected-to-spwc_d_enable_spw_tx_enable_signal>),       //                        .spw_tx_enable_signal
		.spwc_d_leds_spw_red_status_led_signal    (<connected-to-spwc_d_leds_spw_red_status_led_signal>),    //             spwc_d_leds.spw_red_status_led_signal
		.spwc_d_leds_spw_green_status_led_signal  (<connected-to-spwc_d_leds_spw_green_status_led_signal>),  //                        .spw_green_status_led_signal
		.spwc_d_lvds_spw_lvds_p_data_in_signal    (<connected-to-spwc_d_lvds_spw_lvds_p_data_in_signal>),    //             spwc_d_lvds.spw_lvds_p_data_in_signal
		.spwc_d_lvds_spw_lvds_n_data_in_signal    (<connected-to-spwc_d_lvds_spw_lvds_n_data_in_signal>),    //                        .spw_lvds_n_data_in_signal
		.spwc_d_lvds_spw_lvds_p_data_out_signal   (<connected-to-spwc_d_lvds_spw_lvds_p_data_out_signal>),   //                        .spw_lvds_p_data_out_signal
		.spwc_d_lvds_spw_lvds_n_data_out_signal   (<connected-to-spwc_d_lvds_spw_lvds_n_data_out_signal>),   //                        .spw_lvds_n_data_out_signal
		.spwc_d_lvds_spw_lvds_p_strobe_out_signal (<connected-to-spwc_d_lvds_spw_lvds_p_strobe_out_signal>), //                        .spw_lvds_p_strobe_out_signal
		.spwc_d_lvds_spw_lvds_n_strobe_out_signal (<connected-to-spwc_d_lvds_spw_lvds_n_strobe_out_signal>), //                        .spw_lvds_n_strobe_out_signal
		.spwc_d_lvds_spw_lvds_p_strobe_in_signal  (<connected-to-spwc_d_lvds_spw_lvds_p_strobe_in_signal>),  //                        .spw_lvds_p_strobe_in_signal
		.spwc_d_lvds_spw_lvds_n_strobe_in_signal  (<connected-to-spwc_d_lvds_spw_lvds_n_strobe_in_signal>),  //                        .spw_lvds_n_strobe_in_signal
		.spwc_e_enable_spw_rx_enable_signal       (<connected-to-spwc_e_enable_spw_rx_enable_signal>),       //           spwc_e_enable.spw_rx_enable_signal
		.spwc_e_enable_spw_tx_enable_signal       (<connected-to-spwc_e_enable_spw_tx_enable_signal>),       //                        .spw_tx_enable_signal
		.spwc_e_leds_spw_red_status_led_signal    (<connected-to-spwc_e_leds_spw_red_status_led_signal>),    //             spwc_e_leds.spw_red_status_led_signal
		.spwc_e_leds_spw_green_status_led_signal  (<connected-to-spwc_e_leds_spw_green_status_led_signal>),  //                        .spw_green_status_led_signal
		.spwc_e_lvds_spw_lvds_p_data_in_signal    (<connected-to-spwc_e_lvds_spw_lvds_p_data_in_signal>),    //             spwc_e_lvds.spw_lvds_p_data_in_signal
		.spwc_e_lvds_spw_lvds_n_data_in_signal    (<connected-to-spwc_e_lvds_spw_lvds_n_data_in_signal>),    //                        .spw_lvds_n_data_in_signal
		.spwc_e_lvds_spw_lvds_p_data_out_signal   (<connected-to-spwc_e_lvds_spw_lvds_p_data_out_signal>),   //                        .spw_lvds_p_data_out_signal
		.spwc_e_lvds_spw_lvds_n_data_out_signal   (<connected-to-spwc_e_lvds_spw_lvds_n_data_out_signal>),   //                        .spw_lvds_n_data_out_signal
		.spwc_e_lvds_spw_lvds_p_strobe_out_signal (<connected-to-spwc_e_lvds_spw_lvds_p_strobe_out_signal>), //                        .spw_lvds_p_strobe_out_signal
		.spwc_e_lvds_spw_lvds_n_strobe_out_signal (<connected-to-spwc_e_lvds_spw_lvds_n_strobe_out_signal>), //                        .spw_lvds_n_strobe_out_signal
		.spwc_e_lvds_spw_lvds_p_strobe_in_signal  (<connected-to-spwc_e_lvds_spw_lvds_p_strobe_in_signal>),  //                        .spw_lvds_p_strobe_in_signal
		.spwc_e_lvds_spw_lvds_n_strobe_in_signal  (<connected-to-spwc_e_lvds_spw_lvds_n_strobe_in_signal>),  //                        .spw_lvds_n_strobe_in_signal
		.spwc_f_enable_spw_rx_enable_signal       (<connected-to-spwc_f_enable_spw_rx_enable_signal>),       //           spwc_f_enable.spw_rx_enable_signal
		.spwc_f_enable_spw_tx_enable_signal       (<connected-to-spwc_f_enable_spw_tx_enable_signal>),       //                        .spw_tx_enable_signal
		.spwc_f_leds_spw_red_status_led_signal    (<connected-to-spwc_f_leds_spw_red_status_led_signal>),    //             spwc_f_leds.spw_red_status_led_signal
		.spwc_f_leds_spw_green_status_led_signal  (<connected-to-spwc_f_leds_spw_green_status_led_signal>),  //                        .spw_green_status_led_signal
		.spwc_f_lvds_spw_lvds_p_data_in_signal    (<connected-to-spwc_f_lvds_spw_lvds_p_data_in_signal>),    //             spwc_f_lvds.spw_lvds_p_data_in_signal
		.spwc_f_lvds_spw_lvds_n_data_in_signal    (<connected-to-spwc_f_lvds_spw_lvds_n_data_in_signal>),    //                        .spw_lvds_n_data_in_signal
		.spwc_f_lvds_spw_lvds_p_data_out_signal   (<connected-to-spwc_f_lvds_spw_lvds_p_data_out_signal>),   //                        .spw_lvds_p_data_out_signal
		.spwc_f_lvds_spw_lvds_n_data_out_signal   (<connected-to-spwc_f_lvds_spw_lvds_n_data_out_signal>),   //                        .spw_lvds_n_data_out_signal
		.spwc_f_lvds_spw_lvds_p_strobe_out_signal (<connected-to-spwc_f_lvds_spw_lvds_p_strobe_out_signal>), //                        .spw_lvds_p_strobe_out_signal
		.spwc_f_lvds_spw_lvds_n_strobe_out_signal (<connected-to-spwc_f_lvds_spw_lvds_n_strobe_out_signal>), //                        .spw_lvds_n_strobe_out_signal
		.spwc_f_lvds_spw_lvds_p_strobe_in_signal  (<connected-to-spwc_f_lvds_spw_lvds_p_strobe_in_signal>),  //                        .spw_lvds_p_strobe_in_signal
		.spwc_f_lvds_spw_lvds_n_strobe_in_signal  (<connected-to-spwc_f_lvds_spw_lvds_n_strobe_in_signal>),  //                        .spw_lvds_n_strobe_in_signal
		.spwc_g_enable_spw_rx_enable_signal       (<connected-to-spwc_g_enable_spw_rx_enable_signal>),       //           spwc_g_enable.spw_rx_enable_signal
		.spwc_g_enable_spw_tx_enable_signal       (<connected-to-spwc_g_enable_spw_tx_enable_signal>),       //                        .spw_tx_enable_signal
		.spwc_g_leds_spw_red_status_led_signal    (<connected-to-spwc_g_leds_spw_red_status_led_signal>),    //             spwc_g_leds.spw_red_status_led_signal
		.spwc_g_leds_spw_green_status_led_signal  (<connected-to-spwc_g_leds_spw_green_status_led_signal>),  //                        .spw_green_status_led_signal
		.spwc_g_lvds_spw_lvds_p_data_in_signal    (<connected-to-spwc_g_lvds_spw_lvds_p_data_in_signal>),    //             spwc_g_lvds.spw_lvds_p_data_in_signal
		.spwc_g_lvds_spw_lvds_n_data_in_signal    (<connected-to-spwc_g_lvds_spw_lvds_n_data_in_signal>),    //                        .spw_lvds_n_data_in_signal
		.spwc_g_lvds_spw_lvds_p_data_out_signal   (<connected-to-spwc_g_lvds_spw_lvds_p_data_out_signal>),   //                        .spw_lvds_p_data_out_signal
		.spwc_g_lvds_spw_lvds_n_data_out_signal   (<connected-to-spwc_g_lvds_spw_lvds_n_data_out_signal>),   //                        .spw_lvds_n_data_out_signal
		.spwc_g_lvds_spw_lvds_p_strobe_out_signal (<connected-to-spwc_g_lvds_spw_lvds_p_strobe_out_signal>), //                        .spw_lvds_p_strobe_out_signal
		.spwc_g_lvds_spw_lvds_n_strobe_out_signal (<connected-to-spwc_g_lvds_spw_lvds_n_strobe_out_signal>), //                        .spw_lvds_n_strobe_out_signal
		.spwc_g_lvds_spw_lvds_p_strobe_in_signal  (<connected-to-spwc_g_lvds_spw_lvds_p_strobe_in_signal>),  //                        .spw_lvds_p_strobe_in_signal
		.spwc_g_lvds_spw_lvds_n_strobe_in_signal  (<connected-to-spwc_g_lvds_spw_lvds_n_strobe_in_signal>),  //                        .spw_lvds_n_strobe_in_signal
		.spwc_h_enable_spw_rx_enable_signal       (<connected-to-spwc_h_enable_spw_rx_enable_signal>),       //           spwc_h_enable.spw_rx_enable_signal
		.spwc_h_enable_spw_tx_enable_signal       (<connected-to-spwc_h_enable_spw_tx_enable_signal>),       //                        .spw_tx_enable_signal
		.spwc_h_leds_spw_red_status_led_signal    (<connected-to-spwc_h_leds_spw_red_status_led_signal>),    //             spwc_h_leds.spw_red_status_led_signal
		.spwc_h_leds_spw_green_status_led_signal  (<connected-to-spwc_h_leds_spw_green_status_led_signal>),  //                        .spw_green_status_led_signal
		.spwc_h_lvds_spw_lvds_p_data_in_signal    (<connected-to-spwc_h_lvds_spw_lvds_p_data_in_signal>),    //             spwc_h_lvds.spw_lvds_p_data_in_signal
		.spwc_h_lvds_spw_lvds_n_data_in_signal    (<connected-to-spwc_h_lvds_spw_lvds_n_data_in_signal>),    //                        .spw_lvds_n_data_in_signal
		.spwc_h_lvds_spw_lvds_p_data_out_signal   (<connected-to-spwc_h_lvds_spw_lvds_p_data_out_signal>),   //                        .spw_lvds_p_data_out_signal
		.spwc_h_lvds_spw_lvds_n_data_out_signal   (<connected-to-spwc_h_lvds_spw_lvds_n_data_out_signal>),   //                        .spw_lvds_n_data_out_signal
		.spwc_h_lvds_spw_lvds_p_strobe_out_signal (<connected-to-spwc_h_lvds_spw_lvds_p_strobe_out_signal>), //                        .spw_lvds_p_strobe_out_signal
		.spwc_h_lvds_spw_lvds_n_strobe_out_signal (<connected-to-spwc_h_lvds_spw_lvds_n_strobe_out_signal>), //                        .spw_lvds_n_strobe_out_signal
		.spwc_h_lvds_spw_lvds_p_strobe_in_signal  (<connected-to-spwc_h_lvds_spw_lvds_p_strobe_in_signal>),  //                        .spw_lvds_p_strobe_in_signal
		.spwc_h_lvds_spw_lvds_n_strobe_in_signal  (<connected-to-spwc_h_lvds_spw_lvds_n_strobe_in_signal>),  //                        .spw_lvds_n_strobe_in_signal
		.altpll_0_locked_conduit_export           (<connected-to-altpll_0_locked_conduit_export>),           // altpll_0_locked_conduit.export
		.altpll_0_areset_conduit_export           (<connected-to-altpll_0_areset_conduit_export>),           // altpll_0_areset_conduit.export
		.altpll_0_pll_slave_read                  (<connected-to-altpll_0_pll_slave_read>),                  //      altpll_0_pll_slave.read
		.altpll_0_pll_slave_write                 (<connected-to-altpll_0_pll_slave_write>),                 //                        .write
		.altpll_0_pll_slave_address               (<connected-to-altpll_0_pll_slave_address>),               //                        .address
		.altpll_0_pll_slave_readdata              (<connected-to-altpll_0_pll_slave_readdata>),              //                        .readdata
		.altpll_0_pll_slave_writedata             (<connected-to-altpll_0_pll_slave_writedata>)              //                        .writedata
	);

